#!/usr/bin/env python3
# Author: Marcel-Brian Wilkowsky (mawigh)

import argparse;
import os;
import sys;
import ventoyl;

#parser = argparse.ArgumentParser(description="Update ISO image found on a ventoy device");

ventoyu_ascii = """
 _    __           __              __  __
| |  / /__  ____  / /_____  __  __/ / / /
| | / / _ \/ __ \/ __/ __ \/ / / / / / / 
| |/ /  __/ / / / /_/ /_/ / /_/ / /_/ /  
|___/\___/_/ /_/\__/\____/\__, /\____/   
                         /____/          
"""
print(ventoyu_ascii)

ventoy = ventoyl();
ventoy_path = ventoy.find_ventoy_device();
if ventoy_path:
    print(ventoy_path);
